In [29]:
import numpy as np
#（1）创建一个2*2的数组，计算对角线上元素的和。
a = np.array([[1,2],[4,4]])
print(a)
print(np.trace(a))
a_reverse = np.fliplr(a)
print(np.trace(a_reverse))
#（2）创建一个长度为9的一维数据，数组元素0～8，并将它重新变为3*3的二维数。 
b = np.arange(0,9)
print(b)
b1=b.reshape(3,3)
print(b1)
# （3）创建两个3*3的数组，分别将它们合并为3*6、6*3的数组后，拆分为3个数组。
c1 = np.arange(0,9).reshape(3,3)
c2 = np.arange(10,19).reshape(3,3)

d=np.append(c1,c2,axis=0)
e=np.append(c1,c2,axis=1)

print(d)
print(e)

c3,c4,c5 = np.split(c1,[1,2])
print(c3,c4,c5)

[[1 2]
 [4 4]]
5
6
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]
[[0 1 2]] [[3 4 5]] [[6 7 8]]
